test_a_module (test_dbwebb.TestFunc) ... ok
test_b_analyze_text (test_dbwebb.TestFunc) ... ERROR
test_c_list_median (test_dbwebb.TestFunc) ... FAIL
test_d_find_duplicates (test_dbwebb.TestFunc) ... FAIL
test_e_types (test_dbwebb.TestFunc) ... FAIL
test_f_validate_email (test_dbwebb.TestFunc) ... FAIL

======================================================================
ERROR: test_b_analyze_text (test_dbwebb.TestFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/.dbwebb/test_dbwebb.py", line 47, in test_b_analyze_text
    code = exam.analyze_text()
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/exam.py", line 17, in analyze_text
    print(analyze_functions.vowels())
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/analyze_functions.py", line 9, in vowels
    text = read_file().lower()
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/analyze_functions.py", line 37, in read_file
    with open("manifesto.txt", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'manifesto.txt'

======================================================================
FAIL: test_c_list_median (test_dbwebb.TestFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/.dbwebb/test_dbwebb.py", line 57, in test_c_list_median
    self.assertNotEqual(exam.list_median.__doc__.strip(), "Assignment 2")
AssertionError: 'Assignment 2' == 'Assignment 2'

======================================================================
FAIL: test_d_find_duplicates (test_dbwebb.TestFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/.dbwebb/test_dbwebb.py", line 74, in test_d_find_duplicates
    self.assertNotEqual(exam.find_duplicates.__doc__.strip(), "Assignment 3")
AssertionError: 'Assignment 3' == 'Assignment 3'

======================================================================
FAIL: test_e_types (test_dbwebb.TestFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/.dbwebb/test_dbwebb.py", line 90, in test_e_types
    self.assertNotEqual(exam.types.__doc__.strip(), "Assignment 4")
AssertionError: 'Assignment 4' == 'Assignment 4'

======================================================================
FAIL: test_f_validate_email (test_dbwebb.TestFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/efo/dbwebb/lab/config/python/v3/exam/2018-lp1/.dbwebb/test_dbwebb.py", line 109, in test_f_validate_email
    self.assertNotEqual(exam.validate_email.__doc__.strip(), "Assignment 5")
AssertionError: 'Assignment 5' == 'Assignment 5'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4, errors=1)
